# vendored from crate2nix
# Changes made:
# - Fixed support for non-root Git dependencies.
# - Fetch submodules required by Git dependencies.
# - Split library, binary, and test builds for workspace members and the root crate.
# - Set CARGO for all crate builds.
# - Handle self-referential dev dependencies when building tests.
# - Build integration tests against the canonical library derivation.
# - Reuse canonical binaries in integration tests and avoid ordinary library builds in unit tests.
# Build a Rust workspace from pre-resolved JSON (generated by crate2nix --format json).
#
# All dependency resolution, feature expansion, and optional dep activation is
# done in Rust by crate2nix. This file wires the pre-resolved data to
# buildRustCrate and does cheap platform filtering at eval time.
#
# Usage:
#   let
#     cargoNix = import ./build-from-json.nix {
#       inherit pkgs;
#       src = ./.;
#       resolvedJson = ./Cargo.json;
#     };
#   in cargoNix.workspaceMembers.my-crate.build

{
  pkgs ? import <nixpkgs> { },
  lib ? pkgs.lib,
  stdenv ? pkgs.stdenv,
  # Workspace source root (must match the workspace that generated the JSON)
  src,
  # Path to the pre-resolved JSON file
  resolvedJson,
  # Optional: function to create buildRustCrate for a given pkgs
  buildRustCrateForPkgs ? pkgs: pkgs.buildRustCrate,
  # Optional: default crate overrides
  defaultCrateOverrides ? pkgs.defaultCrateOverrides,
  # Optional: tools added to PATH when running test harnesses
  testInputs ? [ ],
  # Optional: environment variables set when running test harnesses
  testEnvironment ? { },
}:

let
  resolved = builtins.fromJSON (builtins.readFile resolvedJson);

  # Source resolution: given a crate's source info, produce a src path.
  # Local paths in the JSON are relative to workspace root.
  resolveSrc =
    crateInfo:
    let
      source = crateInfo.source or null;
      sourceType = if source == null then "local" else source.type or "local";
      relPath = if source == null then "." else source.path or ".";
    in
    if sourceType == "local" then
      if relPath == "." then src else src + "/${relPath}"
    else if sourceType == "crates-io" then
      pkgs.fetchurl {
        name = "${crateInfo.crateName}-${crateInfo.version}.tar.gz";
        url = "https://static.crates.io/crates/${crateInfo.crateName}/${crateInfo.crateName}-${crateInfo.version}.crate";
        sha256 = crateInfo.sha256;
      }
    else if sourceType == "git" then
      let
        gitSrc = pkgs.fetchgit {
          url = source.url;
          rev = source.rev;
          sha256 = crateInfo.sha256;
        };
        allCargoTomls = lib.filter (lib.hasSuffix "Cargo.toml") (lib.filesystem.listFilesRecursive gitSrc);
        getCrateNameFromPath =
          path:
          let
            cargoTomlCrate = builtins.fromTOML (builtins.readFile path);
          in
          cargoTomlCrate.package.name or null;
        packageCargoToml = builtins.head (
          builtins.filter (path: getCrateNameFromPath path == crateInfo.crateName) allCargoTomls
        );
      in
      lib.removeSuffix "Cargo.toml" packageCargoToml
    else
      src;

  # Platform matching: evaluate cfg() strings against stdenv.hostPlatform.
  # This is the cheap O(deps) filtering that stays in Nix.
  platformMatches =
    platform: targetPlatform:
    let
      p = targetPlatform;
      rustTarget = p.rust.rustcTargetSpec or p.rust.rustcTarget or "";
    in
    if platform == null then
      true
    else if lib.hasPrefix "cfg(" platform then
      evalCfg (lib.removePrefix "cfg(" (lib.removeSuffix ")" platform)) p
    else
      # Plain target triple
      platform == rustTarget;

  # Evaluate a cfg expression body (the part inside cfg(...)).
  # Handles: not(...), all(...), any(...), key = "value", name
  evalCfg =
    expr: p:
    let
      stripped = lib.strings.trim expr;
    in
    if lib.hasPrefix "not(" stripped then
      !(evalCfg (lib.removePrefix "not(" (lib.removeSuffix ")" stripped)) p)
    else if lib.hasPrefix "all(" stripped then
      lib.all (e: evalCfg e p) (splitCfgArgs (lib.removePrefix "all(" (lib.removeSuffix ")" stripped)))
    else if lib.hasPrefix "any(" stripped then
      lib.any (e: evalCfg e p) (splitCfgArgs (lib.removePrefix "any(" (lib.removeSuffix ")" stripped)))
    else if lib.hasInfix "=" stripped then
      let
        parts = lib.splitString "=" stripped;
        key = lib.strings.trim (builtins.head parts);
        rawVal = lib.strings.trim (lib.concatStringsSep "=" (builtins.tail parts));
        val = lib.removePrefix "\"" (lib.removeSuffix "\"" rawVal);
      in
      evalCfgKeyValue key val p
    else
      # Bare name like "unix" or "windows"
      evalCfgName stripped p;

  evalCfgName =
    name: p:
    if name == "unix" then
      p.isUnix or false
    else if name == "windows" then
      p.isWindows or false
    else
      false;

  evalCfgKeyValue =
    key: val: p:
    if key == "target_os" then
      (p.parsed.kernel.name or "") == val
      || (val == "macos" && (p.parsed.kernel.name or "") == "darwin")
      || (val == "linux" && p.isLinux or false)
      || (val == "windows" && p.isWindows or false)
    else if key == "target_arch" then
      (p.parsed.cpu.name or "") == val
    else if key == "target_vendor" then
      (p.parsed.vendor.name or p.vendor or "") == val
    else if key == "target_env" then
      (p.parsed.abi.name or "") == val
      || (val == "gnu" && p.isGnu or false)
      || (val == "musl" && p.isMusl or false)
    else if key == "target_family" then
      (val == "unix" && p.isUnix or false) || (val == "windows" && p.isWindows or false)
    else if key == "target_endian" then
      (val == "little" && p.isLittleEndian or false) || (val == "big" && p.isBigEndian or false)
    else if key == "target_pointer_width" then
      (val == "64" && p.is64bit or false) || (val == "32" && p.is32bit or false)
    else
      false;

  # Split comma-separated cfg arguments, respecting parentheses nesting.
  splitCfgArgs =
    s:
    let
      chars = lib.stringToCharacters s;
      result =
        builtins.foldl'
          (
            acc: c:
            if c == "(" then
              acc
              // {
                depth = acc.depth + 1;
                current = acc.current + c;
              }
            else if c == ")" then
              acc
              // {
                depth = acc.depth - 1;
                current = acc.current + c;
              }
            else if c == "," && acc.depth == 0 then
              acc
              // {
                parts = acc.parts ++ [ acc.current ];
                current = "";
              }
            else
              acc // { current = acc.current + c; }
          )
          {
            parts = [ ];
            current = "";
            depth = 0;
          }
          chars;
    in
    result.parts ++ (if result.current != "" then [ result.current ] else [ ]);

  # Filter deps for the given platform
  filterDeps =
    deps: targetPlatform:
    builtins.filter (dep: platformMatches (dep.target or null) targetPlatform) deps;

  # Build the canonical library graph. Each crate derivation also exposes
  # lazy test and binary variants that depend on this graph.
  mkBuiltByPackageIdByPkgs =
    let
      go =
        cratePkgs:
        let
          buildRustCrate =
            let
              base = buildRustCrateForPkgs cratePkgs;
            in
            if defaultCrateOverrides != pkgs.defaultCrateOverrides then
              base.override { defaultCrateOverrides = defaultCrateOverrides; }
            else
              base;

          self = {
            crates = lib.mapAttrs (
              packageId: _: buildCrate self cratePkgs buildRustCrate packageId
            ) resolved.crates;
            build = go cratePkgs.buildPackages;
          };
        in
        self;
    in
    go pkgs;

  buildCrate =
    self: cratePkgs: buildRustCrate: packageId:
    let
      crateInfo = resolved.crates.${packageId};
      targetPlatform = cratePkgs.stdenv.hostPlatform;
      crateBins = crateInfo.crateBin or [ ];
      hasBins = crateBins != [ ];
      crateFeatures = builtins.filter (
        feature: !(lib.hasInfix "/" feature || lib.hasPrefix "dep:" feature)
      ) (crateInfo.resolvedDefaultFeatures or [ ]);
      enabledCrateBins = builtins.filter (
        bin:
        if bin ? requiredFeatures then
          lib.intersectLists bin.requiredFeatures crateFeatures == bin.requiredFeatures
        else
          true
      ) crateBins;
      hasLib =
        (crateInfo.procMacro or false)
        || (crateInfo.libCrateTypes or [ ]) != [ ]
        || (crateInfo.libPath or null) != null
        || (crateInfo.libName or null) != null;

      # Resolve a regular dependency. Proc-macro crates must be built for
      # the build platform since they execute as compiler plugins.
      depDrv =
        dep:
        let
          depCrateInfo = resolved.crates.${dep.packageId} or null;
        in
        if depCrateInfo != null && (depCrateInfo.procMacro or false) then
          self.build.crates.${dep.packageId}
        else
          self.crates.${dep.packageId};

      # Build-script dependencies run on the build platform, so all of
      # them must be built for that platform (not just proc-macros).
      buildDepDrv = dep: self.build.crates.${dep.packageId};

      mkCrate =
        {
          buildTests ? false,
          includeDevDependencies ? false,
          testProfile ? false,
          crateBin ? [ ],
          extraDependencies ? [ ],
        }:
        let
          normalDeps =
            (crateInfo.dependencies or [ ])
            ++ lib.optionals includeDevDependencies (
              builtins.filter (dep: dep.packageId != packageId) (crateInfo.devDependencies or [ ])
            );
          dependencyDrv =
            dep:
            let
              depCrateInfo = resolved.crates.${dep.packageId} or null;
            in
            if testProfile then
              if depCrateInfo != null && (depCrateInfo.procMacro or false) then
                self.build.crates.${dep.packageId}.testLib
              else
                self.crates.${dep.packageId}.testLib
            else
              depDrv dep;
          buildDependencyDrv =
            dep: if testProfile then self.build.crates.${dep.packageId}.testLib else buildDepDrv dep;
          dependencies = extraDependencies ++ map dependencyDrv (filterDeps normalDeps targetPlatform);
          buildDependencies = map buildDependencyDrv (
            filterDeps (crateInfo.buildDependencies or [ ]) targetPlatform
          );
          allDeps = filterDeps (normalDeps ++ (crateInfo.buildDependencies or [ ])) targetPlatform;
          renamedDeps = lib.filter (d: d ? rename && d.rename != null) allDeps;
          crateRenames =
            let
              grouped = lib.groupBy (dep: dep.name) renamedDeps;
              versionAndRename = dep: {
                inherit (dep) rename;
                version = (resolved.crates.${dep.packageId}).version;
              };
            in
            lib.mapAttrs (_name: builtins.map versionAndRename) grouped;
          crateSrc = resolveSrc crateInfo;
          testRustcOpts = [
            "-C opt-level=0"
            "-C codegen-units=256"
            "-C debug-assertions=yes"
            "-C overflow-checks=yes"
          ];
        in
        buildRustCrate (
          {
            crateName = crateInfo.crateName;
            version = crateInfo.version;
            edition = crateInfo.edition or "2021";
            sha256 = crateInfo.sha256 or "";
            src = crateSrc;
            authors = crateInfo.authors or [ ];
            inherit
              dependencies
              buildDependencies
              crateRenames
              crateBin
              ;
            features = crateInfo.resolvedDefaultFeatures or [ ];
            procMacro = crateInfo.procMacro or false;

            # Cargo env vars
            CARGO = lib.getExe cratePkgs.cargo;
          }
          // lib.optionalAttrs buildTests {
            buildTests = true;
          }
          // lib.optionalAttrs testProfile {
            extraRustcOpts = testRustcOpts;
            extraRustcOptsForBuildRs = testRustcOpts;
          }
          // lib.optionalAttrs ((crateInfo.build or null) != null) {
            build = crateInfo.build;
          }
          // lib.optionalAttrs ((crateInfo.libPath or null) != null) {
            libPath = crateInfo.libPath;
          }
          // lib.optionalAttrs ((crateInfo.libName or null) != null) {
            libName = crateInfo.libName;
          }
          // lib.optionalAttrs ((crateInfo.links or null) != null) {
            links = crateInfo.links;
          }
          // lib.optionalAttrs (crateInfo.libCrateTypes or [ ] != [ ]) {
            type = crateInfo.libCrateTypes;
          }
        );

      buildLib = mkCrate { };
      buildTestLib = mkCrate { testProfile = true; };
      unitTests =
        (mkCrate {
          buildTests = true;
          includeDevDependencies = true;
          testProfile = true;
        }).overrideAttrs
          (
            _finalAttrs: previousAttrs: {
              preBuild = (previousAttrs.preBuild or "") + ''
                if [[ -d tests ]]; then
                  mv tests .crate2nix-integration-tests
                fi

                crate2nixLibPath=${lib.escapeShellArg (crateInfo.libPath or "src/lib.rs")}
                if [[ -e "$crate2nixLibPath" ]]; then
                  mv "$crate2nixLibPath" "$crate2nixLibPath.crate2nix"
                fi
              '';
              postBuild = ''
                if [[ -e "$crate2nixLibPath.crate2nix" ]]; then
                  mv "$crate2nixLibPath.crate2nix" "$crate2nixLibPath"
                  build_lib_test "$crate2nixLibPath"
                fi
              ''
              + (previousAttrs.postBuild or "");
            }
          );
      bins = mkCrate { crateBin = crateBins; };
      workspaceManifestLinks = lib.concatMapStrings (
        workspacePackageId:
        let
          workspaceCrate = resolved.crates.${workspacePackageId};
          workspaceSource = workspaceCrate.source or null;
          workspaceSourceType = if workspaceSource == null then "local" else workspaceSource.type or "local";
          workspaceSourcePath = if workspaceSource == null then "." else workspaceSource.path or ".";
        in
        lib.optionalString (workspaceSourceType == "local") ''
          manifestDir=/build/${lib.escapeShellArg workspaceCrate.crateName}
          if [[ -d /build && -w /build && ! -e "$manifestDir" ]]; then
            ${lib.getExe' pkgs.coreutils "ln"} -s \
              "$testRoot"/${lib.escapeShellArg workspaceSourcePath} "$manifestDir"
          fi
        ''
      ) (lib.attrValues resolved.workspaceMembers);
      withTestRunner =
        drv:
        let
          source = crateInfo.source or null;
          sourceType = if source == null then "local" else source.type or "local";
          isLocal = sourceType == "local";
          testSourceRoot = if isLocal then src else resolveSrc crateInfo;
          testSourceRelPath = if isLocal && source != null then source.path or "." else ".";
        in
        drv.overrideAttrs (
          _finalAttrs: previousAttrs: {
            nativeBuildInputs =
              (previousAttrs.nativeBuildInputs or [ ])
              ++ lib.optionals (testInputs != [ ] || testEnvironment != { }) [
                pkgs.makeWrapper
              ];
            postInstall =
              (previousAttrs.postInstall or "")
              + ''
                mkdir -p "$out/bin"
                cat > "$out/bin/test" <<'EOF'
                #!${pkgs.runtimeShell}
                if [[ -n "''${CRATE2NIX_TEST_SOURCE_ROOT:-}" ]]; then
                  testRoot="$CRATE2NIX_TEST_SOURCE_ROOT"
                else
                  testRoot="$(${lib.getExe' pkgs.coreutils "mktemp"} -d \
                    "''${TMPDIR:-/tmp}/crate2nix-${crateInfo.crateName}.XXXXXX")"
                  trap '${lib.getExe' pkgs.coreutils "rm"} -rf "$testRoot"' EXIT
                  ${lib.getExe' pkgs.coreutils "cp"} -R \
                    ${lib.escapeShellArg (toString testSourceRoot)}/. "$testRoot"
                  ${lib.getExe' pkgs.coreutils "chmod"} -R u+w "$testRoot"
                fi

                ${workspaceManifestLinks}

                status=0
                for testExecutable in "@out@"/tests/*; do
                  [[ -x "$testExecutable" ]] || continue
                  printf '\nRunning %s: %s\n' \
                    ${lib.escapeShellArg crateInfo.crateName} "''${testExecutable##*/}"
                  if ! (
                    cd "$testRoot"/${lib.escapeShellArg testSourceRelPath}
                    "$testExecutable" "$@"
                  ); then
                    status=1
                  fi
                done
                exit "$status"
                EOF
                substituteInPlace "$out/bin/test" --replace-fail '@out@' "$out"
                chmod +x "$out/bin/test"
              ''
              + lib.optionalString (testInputs != [ ]) ''
                wrapProgram "$out/bin/test" \
                  --prefix PATH : ${lib.makeBinPath testInputs}
              ''
              + lib.optionalString (testEnvironment != { }) ''
                wrapProgram "$out/bin/test" \
                  ${lib.concatStringsSep " \\\n                    " (
                    lib.mapAttrsToList (
                      name: value: "--set ${lib.escapeShellArg name} ${lib.escapeShellArg (toString value)}"
                    ) testEnvironment
                  )}
              '';
          }
        );
      integrationTests =
        (mkCrate {
          buildTests = true;
          includeDevDependencies = true;
          testProfile = true;
          # Canonical binaries are supplied through target/cargo-bin-exe.
          # Binary test harnesses are compiled separately in postBuild.
          crateBin = [ ];
          extraDependencies = [ buildTestLib ];
        }).overrideAttrs
          (
            _finalAttrs: previousAttrs: {
              preBuild =
                (previousAttrs.preBuild or "")
                + ''
                  crate2nixLibPath=${lib.escapeShellArg (crateInfo.libPath or "src/lib.rs")}
                  if [[ -e "$crate2nixLibPath" ]]; then
                    mv "$crate2nixLibPath" "$crate2nixLibPath.crate2nix"
                  fi
                ''
                + lib.optionalString (enabledCrateBins != [ ]) ''
                  mkdir -p target/cargo-bin-exe
                ''
                + lib.concatMapStringsSep "\n" (
                  bin:
                  let
                    binName = bin.name or crateInfo.crateName;
                  in
                  ''
                    ln -s ${lib.escapeShellArg "${bins}/bin/${binName}"} \
                      target/cargo-bin-exe/${lib.escapeShellArg binName}
                  ''
                ) enabledCrateBins;
              postBuild =
                lib.concatMapStringsSep "\n" (
                  bin:
                  let
                    binName = bin.name or crateInfo.crateName;
                  in
                  ''
                    BIN_NAME=${lib.escapeShellArg binName}
                    ${
                      if bin ? path then
                        "BIN_PATH=${lib.escapeShellArg bin.path}"
                      else
                        ''
                          BIN_PATH=""
                          search_for_bin_path "$BIN_NAME"
                        ''
                    }
                    build_bin_test "$BIN_NAME" "$BIN_PATH"
                  ''
                ) enabledCrateBins
                + (previousAttrs.postBuild or "");
              postInstall = (previousAttrs.postInstall or "") + ''
                if [[ -d ${unitTests}/tests ]]; then
                  mkdir -p "$out/tests"
                  for testExecutable in ${unitTests}/tests/*; do
                    [[ -e "$testExecutable" ]] || continue
                    ln -s "$testExecutable" "$out/tests/$(basename "$testExecutable")"
                  done
                fi
              '';
            }
          );
      tests = withTestRunner (
        if hasLib then
          integrationTests
        else
          mkCrate {
            buildTests = true;
            includeDevDependencies = true;
            testProfile = true;
            crateBin = crateBins;
          }
      );
    in
    buildLib
    // {
      testLib = buildTestLib;
      inherit tests;
    }
    // lib.optionalAttrs hasBins {
      inherit bins;
    };

  builtCrates = mkBuiltByPackageIdByPkgs;

  mkPackageTargets =
    packageId:
    let
      crate = builtCrates.crates.${packageId};
    in
    {
      inherit packageId;
      buildLib = crate;
      buildTests = crate.tests;
    }
    // lib.optionalAttrs (crate ? bins) {
      buildBins = crate.bins;
    };

  workspaceMemberTargets = lib.mapAttrs (
    _name: packageId: mkPackageTargets packageId
  ) resolved.workspaceMembers;

in
{
  workspaceMembers = workspaceMemberTargets;

  rootCrate = if resolved.root != null then mkPackageTargets resolved.root else null;

  allWorkspaceMembers = pkgs.symlinkJoin {
    name = "all-workspace-members";
    paths = lib.mapAttrsToList (
      _name: member: member.buildBins or member.buildLib
    ) workspaceMemberTargets;
  };

  inherit resolved;
  inherit builtCrates;
}
